services:
    networking_form_generator.type.legend_type:
        class: Networking\FormGeneratorBundle\Form\Type\LegendType
        tags:
            - { name: 'form.type', alias: 'form_legend'}


    networking_form_generator.helper.form:
        class: Networking\FormGeneratorBundle\Helper\FormHelper
        arguments: [@mailer, @doctrine, @templating.engine.twig]

    networking_form_generator.admin.form:
        class: Networking\FormGeneratorBundle\Admin\FormAdmin
        arguments: [null, Networking\FormGeneratorBundle\Entity\Form, NetworkingInitCmsBundle:CRUD]
        calls:
            - [setTranslationDomain, ['formGenerator']]
            - [setLanguages, ["%networking_init_cms.page.languages%"]]
            - [setTemplates, [{'edit': 'NetworkingFormGeneratorBundle:Admin:edit.html.twig', 'show': 'NetworkingFormGeneratorBundle:Admin:show.html.twig'}]]
        tags:
            - { name: sonata.admin, manager_type: orm, label: 'form.admin.menu_label', label_translator_strategy: sonata.admin.label.strategy.underscore, persist_filters: true }

    networking_form_generator.helper.twig:
        class: Networking\FormGeneratorBundle\Twig\Extension\FormHelperExtension
        calls:
            - [setcontainer, ['@service_container']]
        tags:
            - { name: twig.extension }