services:

    Networking\FormGeneratorBundle\Form\Type\LegendType:
        autowire: true
        public: true
        tags:
            - { name: 'form.type', alias: 'form_legend'}


    Networking\FormGeneratorBundle\Helper\FormHelper:
        autowire: true

    Networking\FormGeneratorBundle\Controller\FormAdminController:
          autowire: true
          public: true
          tags:
              - { name: 'controller.service_arguments'}


    Networking\FormGeneratorBundle\Admin\FormAdmin:
        arguments: [null, Networking\FormGeneratorBundle\Entity\Form, NetworkingInitCmsBundle:CRUD]
        calls:
            - [setTranslationDomain, ['formGenerator']]
            - [setLanguages, ["%networking_init_cms.page.languages%"]]
            - [setTemplates, [{'edit': 'NetworkingFormGeneratorBundle:Admin:edit.html.twig', 'show': 'NetworkingFormGeneratorBundle:Admin:show.html.twig'}]]
        tags:
            - { name: sonata.admin, manager_type: orm, label: 'form.admin.menu_label', label_translator_strategy: sonata.admin.label.strategy.underscore, persist_filters: true }

    networking_form_generator.helper.twig:
        class: Networking\FormGeneratorBundle\Twig\Extension\FormHelperExtension
        calls:
            - [setcontainer, ['@service_container']]
        tags:
            - { name: twig.extension }