doctrine:
    orm:
        entity_managers:
            default:
                mappings:
                    NetworkingFormGeneratorBundle:
                        type: annotation
                        prefix: "Networking\\FormGeneratorBundle\\Model"
                        dir: '%kernel.project_dir%/vendor/networking/form-generator-bundle/src/Model'