doctrine:
    orm:
        entity_managers:
            default:
                mappings:
                    NetworkingFormGeneratorBundle:
                        type: annotation
                        prefix: "Networking\\FormGeneratorBundle\\Model"
                        dir: '/Model'