services:

    # default configuration for services in *this* file
    _defaults:
        # automatically injects dependencies in your services
        autowire: true
        # automatically registers your services as commands, event subscribers, etc.
        autoconfigure: true
        # this means you cannot fetch services directly from the container via $container->get()
        # if you need to do this, you can override this setting on individual services
        public: false


    Networking\FormGeneratorBundle\Form\Type\LegendType:
        autowire: true
        public: true
        tags:
            - { name: 'form.type', alias: 'form_legend'}

    Networking\FormGeneratorBundle\Form\FormType:
        public: true
        tags:
            - { name: 'form.type', alias: 'generated_form'}


    Networking\FormGeneratorBundle\Helper\FormHelper:
        autowire: true

    networking_form_generator.helper.form:
          alias: Networking\FormGeneratorBundle\Helper\FormHelper
          public: true

    Networking\FormGeneratorBundle\Controller\FormAdminController:
          autowire: true
          public: true
          tags:
              - { name: 'controller.service_arguments'}

    Networking\FormGeneratorBundle\Controller\FrontendFormController:
          autowire: true
          public: true
          arguments:
              $emailAddress: '%form_generator_from_email%'
          tags:
              - { name: 'controller.service_arguments'}


    Networking\FormGeneratorBundle\Admin\FormAdmin:
        arguments: [null, Networking\FormGeneratorBundle\Entity\Form, NetworkingInitCmsBundle:CRUD]
        calls:
            - [setTranslationDomain, ['formGenerator']]
            - [setSonataAnnotationReader, ['@ibrows_sonataadmin.annotation.reader']]
            - [setLanguages, ["%networking_init_cms.page.languages%"]]
            - [setTemplates, [{'edit': '@@NetworkingFormGenerator/Admin/edit.html.twig', 'show': '@@NetworkingFormGenerator/Admin/show.html.twig'}]]
        tags:
            - { name: sonata.admin, manager_type: orm, label: 'form.admin.menu_label', label_translator_strategy: sonata.admin.label.strategy.underscore, persist_filters: true }

    networking_form_generator.helper.twig:
        class: Networking\FormGeneratorBundle\Twig\Extension\FormHelperExtension
        calls:
            - [setcontainer, ['@service_container']]
        tags:
            - { name: twig.extension }