Networking\FormGeneratorBundle\Model\Form:
    properties:
        id:
            type: integer
        form:
            exclude: true
        name:
            type: string
        infoText:
            type: string
        options:
            type: string
        formData:
            exclude: true
        collection:
            type: array
